TestTask/TestTask/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('product.urls', namespace='products')),
    url(r'^accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TestTask/product/urls.py
from django.conf.urls import url

from . import views

app_name = 'product'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^products/$', views.CategoriesView.as_view(), name='categories'),
    url(r'^products/products24h/$', views.Products24hView.as_view(), name='products24h'),
    url(r'^products/(?P<category_slug>[\w-]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^products/(?P<category_slug>[\w-]+)/(?P<product_slug>[\w-]+)/$', views.AboutView.as_view(), name='about'),

]

TestTask/product/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=40)
    description = models.TextField(default='')

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name



class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=40)
    description = models.TextField(default='')
    price = models.DecimalField(max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

TestTask/product/views.py
from django.views import generic
from .models import Category, Product
from datetime import datetime, timedelta

class IndexView(generic.ListView):
    template_name = 'product/index.html'

    def get_queryset(self):
        pass

class CategoriesView(generic.ListView):
    template_name = 'product/categories.html'
    context_object_name = 'category_list'

    def get_queryset(self):
        return Category.objects.all()

class DetailView(generic.DetailView):
    model = Category
    template_name = 'product/detail.html'
    slug_url_kwarg = 'category_slug'

class AboutView(generic.DetailView):
    model = Product
    template_name = 'product/about.html'
    slug_url_kwarg = 'product_slug'

class Products24hView(generic.ListView):
    template_name = 'product/products24h.html'
    context_object_name = 'products24h_list'

    def get_queryset(self):
        how_many_days = 1
        return Product.objects.filter(created_at__gte=datetime.now()-timedelta(how_many_days))

TestTask/product/templates/product/about.html
{% extends 'product/base.html' %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block body %}
    <h4>Name: {{product.name}}</h4>
    <p>Description: </p>
    <pre>{{product.description}}</pre>
    <p>Price: {{product.price}}</p>
{% endblock %}

TestTask/product/templates/product/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Site{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'product/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse ">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'product:index' %}">
                    <span class="navbar-brand glyphicon glyphicon-home" ></span>
                </a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">

                    <li class="">
                        <a href="{% url 'product:categories' %}">
                            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Categories
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'product:products24h' %}">
                            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>&nbsp; Products24h
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    </li>
                    {% if user.is_authenticated %}
                    <li class="">
                        <a style="color: white">{{ user.get_username }}</a>
                    <li class="">

                            <a href="{% url 'account_logout' %}">
                                <span class="glyphicon glyphicon-log-in " aria-hidden="true"></span>&nbsp; Log Out
                            </a>

                    {% else %}
                    <li class="">
                        <a href="{% url 'account_signup' %}">
                            <span class="" aria-hidden="true"></span>Registration
                        </a>
                    <li class="">
                        <a href="{% url 'account_login' %}">
                             <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; LogIn
                        </a>
                    {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container main-content" style="margin-left:50px; margin-top: 50px">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

TestTask/product/templates/product/categories.html
{% extends 'product/base.html' %}


{% block title %}
Categories
{% endblock %}

{% block body %}
{% if category_list %}

    {% for category in category_list %}
        <h4><a href="{% url 'product:detail' category.slug %}">{{ category.name }}</a></h4>
        <p>Slug: {{category.slug}}</p>
        <p>Description:</p>
        <pre>{{category.description}}</pre>
        <br>
    {% endfor %}

{% else %}
    <p>No category are available.</p>
{% endif %}
{% endblock %}

TestTask/product/templates/product/detail.html
{% extends 'product/base.html' %}


{% block title %}
Products
{% endblock %}

{% block body %}

        {% for product in category.product_set.all %}
            <h4><a href="{% url 'product:about' category.slug product.slug %}">{{ product.name}}</a></h4>
            <p>Description:
            <pre>{{product.description}}</pre>
            <p>Price: {{product.price}}</p>
            <br>
        {% endfor %}

{% endblock %}

TestTask/product/templates/product/index.html
{% extends 'product/base.html' %}

{% block title %}HomePage{% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row col-sm-offset-5 col-sm-7">
     <div class="well">
        <h4>Welcome to home page.</h4>
         <p>Make your choice:
             <a href="{% url 'product:categories' %}">Categories</a>
             or <a href="{% url 'products:products24h' %}">Products are added within 24 hours</a>.
             <br>
             <br>
             <br>
             {% if user.is_authenticated %}
             You Log in. You can visit Products 24h.
             {% else %}
             (But if you want see page with products, you must
             <a href="{% url 'account_login' %}">Log in</a> account or
             <a href="{% url 'account_signup' %}">Register</a> new)
             {% endif %}
         </p>
     </div>
  </div>
</div>
{% endblock %}

TestTask/product/templates/product/products24h.html
{% extends 'product/base.html' %}

{% block title %}
Products24h
{% endblock %}


{% block body %}
    {% if user.is_authenticated %}
            {% if products24h_list %}

                {% for product in products24h_list %}
                    <h4>{{ product.name }}</h4>
                    <p>Slug: {{product.slug}}</p>
                    <p>Description: </p>
                    <pre>{{product.description}}</pre>
                    <br>
                {% endfor %}

            {% else %}
                <p>No products are available.</p>
            {% endif %}
    {% else %}
        <h4>Welcome, user. Please <a href="{% url 'account_login' %}">Log In</a> to this page.</h4>
     {% endif %}
{% endblock %}